volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
        image: itapiru-php:8.4
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            APP_ENV: development
            APP_BASE_PATH: ""
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
